# Generated by Django 3.0.4 on 2020-03-11 21:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200310_1647'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='genre_preferences',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='watched_list',
            field=models.ManyToManyField(to='app.Movie'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.ManyToManyField(related_name='films', to='app.Genre'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='user',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='genre_preference',
            field=models.ManyToManyField(to='app.Genre'),
        ),
    ]
